### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by santaclose** [DanysysTeam/SFTA#8]
Not sure about this programming language? am i supposed to download a compiler from this website? https://www.purebasic.com/
Thanks in advance

**Comment by Danyfirex** [comment]
It does not require special build instructions. You just need to open with the IDE and press F5.

**Comment by steviator** [comment]
Just tried this. Doesn't work. 
 
Error is "Line 623: IsUserAdmin_() is not a function, array, list, map or macro."

Wouldn't it be easier if you just distributed a compiled binary instead of relying on the language to remain unchanged and the compiler to remain available for all of eternity?

This is becoming unbelievable, I just need to be able to change filetype in windows from the command line and I have been working at this problem for hours now, Microsoft broke their own command line tools to do it, changing via reg commands gets instantly reverted.

Please, please, please put a compiled binary somewhere! This joke isn't funny anymore.

**Comment by Danyfirex** [comment]
Hello @steviator, I am very sorry for your inconvenience. This is a project I did for fun so don't expect any update from it. If you want you can use the PowerShell version which doesn't need any compilation and you can also run it from the console easily.
